# -------- Base image --------
FROM node:20-alpine AS base
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# For some Node modules requiring glibc compatibility
RUN apk add --no-cache libc6-compat
WORKDIR /app

# -------- Deps (restore & cache) --------
FROM base AS deps
# Use pnpm via Corepack
RUN corepack enable
# Only lockfile & manifest for better layer caching
COPY package.json pnpm-lock.yaml* ./
# Pre-fetch deps into pnpm store (fast, cacheable)
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm fetch

# -------- Builder --------
FROM base AS builder
RUN corepack enable
WORKDIR /app
# Reuse cached pnpm store from deps stage
COPY package.json pnpm-lock.yaml* ./
# Install deps fully but offline (from fetched store)
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --prefer-offline
# Copy the rest of your source code
COPY . .
# Build Next.js (recommend `output: 'standalone'` in next.config.*)
RUN pnpm build

# -------- Runtime (tiny, secure) --------
FROM node:20-alpine AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app
RUN apk add --no-cache libc6-compat
# Run as non-root for security (user `node` exists in official image)
USER node
# Copy standalone server output & static assets
COPY --chown=node:node --from=builder /app/.next/standalone ./
COPY --chown=node:node --from=builder /app/.next/static ./.next/static
COPY --chown=node:node --from=builder /app/public ./public

# Network
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Start the server generated by Next standalone build
CMD ["node", "server.js"]