# -------- Base image --------
# Pin to specific version for reproducibility and security
FROM node:20.18.0-alpine AS base
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# For some Node modules requiring glibc compatibility
RUN apk add --no-cache libc6-compat
WORKDIR /app

# -------- Deps (restore & cache) --------
FROM base AS deps
# Use pnpm via Corepack
RUN corepack enable
# Only lockfile & manifest for better layer caching
COPY package.json pnpm-lock.yaml* ./
# Pre-fetch deps into pnpm store (fast, cacheable)
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm fetch

# -------- Builder --------
FROM base AS builder
RUN corepack enable
WORKDIR /app
# Reuse cached pnpm store from deps stage
COPY package.json pnpm-lock.yaml* ./
# Install deps fully but offline (from fetched store)
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --prefer-offline
# Copy the rest of your source code
COPY . .
# Build Next.js with standalone output for Docker
ENV DOCKER_BUILD=true
RUN pnpm build

# -------- Runtime (tiny, secure) --------
# Pin to specific version for reproducibility and security
FROM node:20.18.0-alpine AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

# Install minimal dependencies
RUN apk add --no-cache libc6-compat curl

# Create non-root user with specific UID/GID for better security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Run as non-root for security
USER nextjs

# Copy standalone server output & static assets with proper ownership
COPY --chown=nextjs:nodejs --from=builder /app/.next/standalone ./
COPY --chown=nextjs:nodejs --from=builder /app/.next/static ./.next/static
COPY --chown=nextjs:nodejs --from=builder /app/public ./public

# Network
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Health check (using curl which is now installed)
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1

# Start the server generated by Next standalone build
CMD ["node", "server.js"]
